### ISSUE TITLE
Error on tuple declarations

### ISSUE THREAD

**Issue by wreuven** [badicsalex/json_schema_to_c#50]
For the following minimalistic array of object, I get the error:

`Schema error in '.properties.people.items': '[OrderedDict([('type', 'object'), ('properties', OrderedDict([('age', OrderedDict([('type', 'integer')]))]))])]' is not a type descriptor (dict including the field 'type')
`
```
{
  "$id": "/schemas/player",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "people": {
      "type": "array",
      "maxItems": 10,
      "items": [
        {
          "type": "object",
          "properties": {
            "age": {
              "type": "integer"
            }
          }
        }
      ]
    }
  }
}
```

**Comment by badicsalex** [comment]
Tuples (when "items" is an array) are unfortunately unsupported. Are you sure you didn't want to write the following instead?

```
{
  "$id": "/schemas/player",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "people": {
      "type": "array",
      "maxItems": 10,
      "items": {
        "type": "object",
        "properties": {
          "age": {
            "type": "integer"
          }
        }
      }
    }
  }
}
```

I should probably document that tuples are not supported, and have a more helpful error message.

**Comment by badicsalex** [comment]
If you actually wanted tuple support, please reopen the ticket.
